title: Advantages of working in Hero Unit
author: jcrisanto
email: jcrisanto0@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The advantages of working for Hero Unit and Acklen Avenue

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
